import type { Expense, Group, UserSummary } from '@/types'

export const MOCK_USERS: UserSummary[] = [
  {
    id: 'user1',
    name: 'Alice Silva',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
  },
  {
    id: 'user2',
    name: 'Bruno Santos',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bruno',
  },
  {
    id: 'user3',
    name: 'Carolina Oliveira',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carolina',
  },
  {
    id: 'user4',
    name: 'Daniel Costa',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel',
  },
]

export const MOCK_GROUPS: Group[] = [
  {
    id: 'group1',
    name: 'Viagem Rio',
    description: 'Viagem para o Rio de Janeiro',
    coverImageUrl: 'https://images.unsplash.com/photo-1483729558449-99daa71afcc8?w=500',
    members: MOCK_USERS.slice(0, 3),
    createdBy: 'user1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'group2',
    name: 'Apartamento Compartilhado',
    description: 'Despesas do apartamento 302',
    coverImageUrl: 'https://images.unsplash.com/photo-1540932239986-310128078ceb?w=500',
    members: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[3]],
    createdBy: 'user1',
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2024-01-20'),
  },
]

export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'exp1',
    groupId: 'group1',
    title: 'Hotel Copacabana',
    amount: 1500,
    currency: 'BRL',
    category: 'accommodation',
    paidBy: 'user1',
    participants: [
      { userId: 'user1', share: 500, paid: false },
      { userId: 'user2', share: 500, paid: false },
      { userId: 'user3', share: 500, paid: false },
    ],
    splitMethod: 'equal',
    date: new Date('2024-01-15'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'exp2',
    groupId: 'group1',
    title: 'Aluguel de carro',
    amount: 800,
    currency: 'BRL',
    category: 'transport',
    paidBy: 'user2',
    participants: [
      { userId: 'user1', share: 400, paid: false },
      { userId: 'user2', share: 200, paid: false },
      { userId: 'user3', share: 200, paid: false },
    ],
    splitMethod: 'exact',
    date: new Date('2024-01-16'),
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'exp3',
    groupId: 'group1',
    title: 'Refeições no Leblon',
    amount: 420.5,
    currency: 'BRL',
    category: 'food',
    paidBy: 'user3',
    participants: [
      { userId: 'user1', share: 140.17, paid: false },
      { userId: 'user2', share: 140.17, paid: false },
      { userId: 'user3', share: 140.16, paid: false },
    ],
    splitMethod: 'equal',
    date: new Date('2024-01-16'),
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: 'exp4',
    groupId: 'group1',
    title: 'Ingresso Pão de Açúcar',
    amount: 200,
    currency: 'BRL',
    category: 'entertainment',
    paidBy: 'user1',
    participants: [
      { userId: 'user1', share: 50, paid: false },
      { userId: 'user2', share: 75, paid: false },
      { userId: 'user3', share: 75, paid: false },
    ],
    splitMethod: 'exact',
    date: new Date('2024-01-17'),
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: 'exp5',
    groupId: 'group2',
    title: 'Aluguel janeiro',
    amount: 3000,
    currency: 'BRL',
    category: 'utilities',
    paidBy: 'user1',
    participants: [
      { userId: 'user1', share: 1000, paid: false },
      { userId: 'user2', share: 1000, paid: false },
      { userId: 'user4', share: 1000, paid: false },
    ],
    splitMethod: 'equal',
    date: new Date('2024-01-01'),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'exp6',
    groupId: 'group2',
    title: 'Conta de luz',
    amount: 350,
    currency: 'BRL',
    category: 'utilities',
    paidBy: 'user2',
    participants: [
      { userId: 'user1', share: 116.67, paid: false },
      { userId: 'user2', share: 116.67, paid: false },
      { userId: 'user4', share: 116.66, paid: false },
    ],
    splitMethod: 'equal',
    date: new Date('2024-01-10'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'exp7',
    groupId: 'group2',
    title: 'Supermercado',
    amount: 487.89,
    currency: 'BRL',
    category: 'shopping',
    paidBy: 'user4',
    participants: [
      { userId: 'user1', share: 150, paid: false },
      { userId: 'user2', share: 200, paid: false },
      { userId: 'user4', share: 137.89, paid: false },
    ],
    splitMethod: 'exact',
    date: new Date('2024-01-12'),
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'exp8',
    groupId: 'group2',
    title: 'Gás e água',
    amount: 150,
    currency: 'BRL',
    category: 'utilities',
    paidBy: 'user1',
    participants: [
      { userId: 'user1', share: 50, paid: false },
      { userId: 'user2', share: 50, paid: false },
      { userId: 'user4', share: 50, paid: false },
    ],
    splitMethod: 'equal',
    date: new Date('2024-01-14'),
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
]
